async function sendEmployeeNotification(employeeEmail, visitor) {
    const approveLink =
        `https://visitor-management-jp03.onrender.com/visitor/approve-mail/${visitor.id}?token=${visitor.token}`;

    const rejectLink =
        `https://visitor-management-jp03.onrender.com/visitor/reject-mail/${visitor.id}?token=${visitor.token}`;
    const response = await fetch(
        'https://api.brevo.com/v3/smtp/email',
        {
            method: 'POST',
            headers: {
                'accept': 'application/json',
                'api-key': process.env.BREVO_API_KEY,
                'content-type': 'application/json'
            },
            body: JSON.stringify({
                sender: {
                    email: 'anandkm539@gmail.com',
                    name: 'Visitor Management System'
                },
                to: [
                    {
                        email: employeeEmail
                    }
                ],
                subject: 'New Visitor Registration',
                htmlContent: `
<div style="max-width:650px;margin:auto;font-family:Arial,sans-serif;background:#f4f6f9;padding:30px;">

    <div style="background:#111827;color:white;padding:20px;text-align:center;border-radius:12px 12px 0 0;">
        <h1 style="margin:0;">Visitor Management System</h1>
        <p style="margin-top:8px;color:#d1d5db;">
            New Visitor Approval Request
        </p>
    </div>

    <div style="background:white;padding:30px;border-radius:0 0 12px 12px;">

        <h2 style="color:#111827;">
            Hello,
        </h2>

        <p>
            A new visitor has requested access to the premises.
            Please review the details below.
        </p>

        <table style="width:100%;border-collapse:collapse;margin-top:20px;">

            <tr>
                <td style="padding:12px;font-weight:bold;">Visitor Name</td>
                <td>${visitor.name}</td>
            </tr>

            <tr style="background:#f9fafb;">
                <td style="padding:12px;font-weight:bold;">Phone</td>
                <td>${visitor.phone}</td>
            </tr>

            <tr>
                <td style="padding:12px;font-weight:bold;">Email</td>
                <td>${visitor.email}</td>
            </tr>

            <tr style="background:#f9fafb;">
                <td style="padding:12px;font-weight:bold;">Purpose</td>
                <td>${visitor.purpose}</td>
            </tr>

        </table>

        <div style="margin-top:35px;text-align:center;">

            <a href="${approveLink}"
               style="
               background:#16a34a;
               color:white;
               padding:14px 30px;
               text-decoration:none;
               border-radius:8px;
               font-weight:bold;
               display:inline-block;
               margin-right:15px;">
               ✅ APPROVE
            </a>

            <a href="${rejectLink}"
               style="
               background:#dc2626;
               color:white;
               padding:14px 30px;
               text-decoration:none;
               border-radius:8px;
               font-weight:bold;
               display:inline-block;">
               ❌ REJECT
            </a>

        </div>

        <hr style="margin:40px 0;">

        <p style="color:#6b7280;font-size:13px;text-align:center;">
            This email was automatically generated by the
            Visitor Management System.<br>
            Please do not reply to this email.
        </p>

    </div>

</div>
`
            })
        }
    );

    const data = await response.json();
    console.log('Employee Email:', data);
}

async function sendVisitorPassEmail(
    visitorEmail,
    visitorName,
    visitorId,
    passId
) {

    const passLink =
        `https://visitor-management-jp03.onrender.com/visitor-pass.html?id=${visitorId}`;

    const response = await fetch(
        'https://api.brevo.com/v3/smtp/email',
        {
            method: 'POST',
            headers: {
                'accept': 'application/json',
                'api-key': process.env.BREVO_API_KEY,
                'content-type': 'application/json'
            },
            body: JSON.stringify({
                sender: {
                    email: 'anandkm539@gmail.com',
                    name: 'Visitor Management System'
                },
                to: [
                    {
                        email: visitorEmail
                    }
                ],
                subject: 'Visitor Pass Approved',
                htmlContent: `
<div style="max-width:650px;margin:auto;font-family:Arial,sans-serif;background:#f4f6f9;padding:30px;">

    <div style="background:#111827;color:white;padding:20px;text-align:center;border-radius:12px 12px 0 0;">
        <h1 style="margin:0;">Visitor Management System</h1>
        <p style="margin-top:8px;color:#d1d5db;">
            Visitor Pass Approved
        </p>
    </div>

    <div style="background:white;padding:30px;border-radius:0 0 12px 12px;">

        <h2>Hello ${visitorName},</h2>

        <p>
            Your visitor request has been approved.
        </p>

        <table style="width:100%;margin-top:20px;border-collapse:collapse;">

            <tr>
                <td style="padding:12px;font-weight:bold;">Pass ID</td>
                <td>${passId}</td>
            </tr>

            <tr style="background:#f9fafb;">
                <td style="padding:12px;font-weight:bold;">Status</td>
                <td style="color:#16a34a;font-weight:bold;">
                    Approved
                </td>
            </tr>

        </table>

        <div style="margin-top:35px;text-align:center;">

            <a href="${passLink}"
               style="
               background:#2563eb;
               color:white;
               padding:14px 35px;
               border-radius:8px;
               text-decoration:none;
               font-weight:bold;">
               View Visitor Pass
            </a>

        </div>

        <p style="margin-top:30px;">
            Please keep your visitor pass ready while entering the premises.
        </p>

        <hr style="margin:40px 0;">

        <p style="color:#6b7280;font-size:13px;text-align:center;">
            This email was automatically generated by the
            Visitor Management System.
        </p>

    </div>

</div>
`
            })
        }
    );

    const data = await response.json();
    console.log('Visitor Email:', data);
}

module.exports = {
    sendEmployeeNotification,
    sendVisitorPassEmail
};